import { Client } from '@notionhq/client';
import type { ConsolidatedPage, PipelineState } from './types';

const DELAY_MS = 350; // Notion rate limit: ~3 req/sec

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function splitIntoBlocks(content: string): any[] {
  const lines = content.split('\n');
  const blocks: any[] = [];

  for (const line of lines) {
    if (!line.trim()) continue;

    // Heading detection
    if (line.startsWith('### ')) {
      blocks.push({
        object: 'block',
        type: 'heading_3',
        heading_3: { rich_text: [{ type: 'text', text: { content: line.slice(4).trim() } }] },
      });
    } else if (line.startsWith('## ')) {
      blocks.push({
        object: 'block',
        type: 'heading_2',
        heading_2: { rich_text: [{ type: 'text', text: { content: line.slice(3).trim() } }] },
      });
    } else if (line.startsWith('# ')) {
      blocks.push({
        object: 'block',
        type: 'heading_1',
        heading_1: { rich_text: [{ type: 'text', text: { content: line.slice(2).trim() } }] },
      });
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      blocks.push({
        object: 'block',
        type: 'bulleted_list_item',
        bulleted_list_item: { rich_text: [{ type: 'text', text: { content: line.slice(2).trim() } }] },
      });
    } else if (line.startsWith('---')) {
      blocks.push({
        object: 'block',
        type: 'divider',
        divider: {},
      });
    } else {
      // Notion rich_text has a 2000 char limit per text object
      const chunks = chunkText(line, 2000);
      blocks.push({
        object: 'block',
        type: 'paragraph',
        paragraph: {
          rich_text: chunks.map((c) => ({ type: 'text', text: { content: c } })),
        },
      });
    }
  }

  return blocks;
}

function chunkText(text: string, maxLen: number): string[] {
  const chunks: string[] = [];
  for (let i = 0; i < text.length; i += maxLen) {
    chunks.push(text.slice(i, i + maxLen));
  }
  return chunks.length > 0 ? chunks : [''];
}

export async function findOrCreateParentPage(client: Client): Promise<string> {
  // Search for existing "Cleansed Data" page
  const search = await client.search({
    query: 'Cleansed Data',
    filter: { property: 'object', value: 'page' },
    page_size: 5,
  });

  for (const result of search.results) {
    const page = result as any;
    const title = page.properties?.title?.title?.[0]?.plain_text
      || page.properties?.Name?.title?.[0]?.plain_text
      || '';
    if (title === 'Cleansed Data') {
      console.log(`[consolidation] Found existing "Cleansed Data" page: ${page.id}`);
      return page.id;
    }
  }

  // Not found — find an accessible page to nest under.
  // Internal Notion integrations cannot create workspace-level pages.
  // We must create "Cleansed Data" as a child of an existing accessible page.
  const topPages = await client.search({
    filter: { property: 'object', value: 'page' },
    page_size: 10,
  });

  const accessible = topPages.results as any[];
  // Prefer pages that are themselves at workspace root (cleanest hierarchy)
  const bestParent = accessible.find(p => p.parent?.type === 'workspace') ?? accessible[0];

  if (!bestParent) {
    throw new Error(
      'No accessible Notion pages found. Share at least one page with the Melvin integration ' +
      'in Notion settings, then re-run consolidation.',
    );
  }

  const parentId: string = bestParent.id;
  console.log(`[consolidation] Creating "Cleansed Data" under Notion page ${parentId}`);

  const page = await client.pages.create({
    parent: { page_id: parentId },
    properties: {
      title: { title: [{ text: { content: 'Cleansed Data' } }] },
    },
    children: [{
      object: 'block' as const,
      type: 'callout' as const,
      callout: {
        rich_text: [{ type: 'text' as const, text: { content: 'Consolidated knowledge base — auto-generated by Melvin. This is the source of truth.' } }],
        icon: { type: 'emoji' as const, emoji: '\u{1F9F9}' as any },
      },
    }],
  });

  console.log(`[consolidation] Created "Cleansed Data" page: ${page.id}`);
  return page.id;
}

async function createChildPage(
  client: Client,
  parentId: string,
  title: string,
  content: string,
  metadata?: { sourceCount?: number; category?: string },
): Promise<string> {
  const blocks = splitIntoBlocks(content);

  // Notion limits to 100 blocks per create call
  const initialBlocks = blocks.slice(0, 100);
  const remainingBlocks = blocks.slice(100);

  const page = await client.pages.create({
    parent: { page_id: parentId },
    properties: {
      title: { title: [{ text: { content: title } }] },
    },
    children: initialBlocks,
  });

  // Append remaining blocks in batches
  for (let i = 0; i < remainingBlocks.length; i += 100) {
    const batch = remainingBlocks.slice(i, i + 100);
    await new Promise((r) => setTimeout(r, DELAY_MS));
    await client.blocks.children.append({
      block_id: page.id,
      children: batch,
    });
  }

  return page.id;
}

/** Returns all child topic pages under the "Cleansed Data" parent (excludes summary pages). */
export async function listExistingTopicPages(
  client: Client,
  parentPageId: string,
): Promise<{ title: string; pageId: string }[]> {
  const topics: { title: string; pageId: string }[] = [];

  let cursor: string | undefined;
  do {
    const res = await client.blocks.children.list({
      block_id: parentPageId,
      page_size: 100,
      ...(cursor ? { start_cursor: cursor } : {}),
    });

    for (const block of res.results) {
      const b = block as any;
      if (b.type !== 'child_page') continue;
      const title: string = b.child_page?.title || '';
      // Skip the rolling summary pages
      if (title.startsWith('Consolidation —') || title === 'Cleansed Data') continue;
      topics.push({ title, pageId: b.id });
    }

    cursor = res.next_cursor ?? undefined;
  } while (cursor);

  return topics;
}

/** Fetch text content from a Notion page (first 100 blocks). */
export async function fetchPageTextContent(client: Client, pageId: string): Promise<string> {
  try {
    const blocks = await client.blocks.children.list({ block_id: pageId, page_size: 100 });
    const parts: string[] = [];

    for (const block of blocks.results) {
      const b = block as any;
      const richText =
        b.paragraph?.rich_text ||
        b.heading_1?.rich_text ||
        b.heading_2?.rich_text ||
        b.heading_3?.rich_text ||
        b.bulleted_list_item?.rich_text ||
        b.numbered_list_item?.rich_text ||
        b.quote?.rich_text ||
        b.callout?.rich_text ||
        [];
      const text = richText.map((r: any) => r.plain_text).join('');
      if (text) parts.push(text);
    }

    return parts.join('\n');
  } catch {
    return '';
  }
}

/**
 * Archive the old page and create a fresh one under the same parent with updated content.
 * Notion's version history preserves the old content for rollback.
 */
export async function archiveAndRecreatePage(
  client: Client,
  oldPageId: string,
  parentId: string,
  title: string,
  content: string,
): Promise<string> {
  await client.pages.update({ page_id: oldPageId, archived: true });
  await new Promise((r) => setTimeout(r, DELAY_MS));
  return createChildPage(client, parentId, title, content);
}

/**
 * Incremental Notion write: update existing topic pages and create new ones.
 * Called instead of writeToNotion when mode is incremental.
 */
export async function writeToNotionIncremental(
  updates: { pageId: string; title: string; content: string }[],
  newPages: ConsolidatedPage[],
  parentId: string,
  userId: string,
  state: PipelineState,
): Promise<void> {
  const { getUncachableNotionClient } = await import('../../notion-service');
  const client = await getUncachableNotionClient(userId);

  // Update existing pages (archive old + recreate with merged content)
  for (const update of updates) {
    console.log(`[consolidation] Updating Notion page: "${update.title}"`);
    try {
      await archiveAndRecreatePage(client, update.pageId, parentId, update.title, update.content);
      state.pagesCreated++;
    } catch (err) {
      const msg = `Failed to update "${update.title}": ${err instanceof Error ? err.message : err}`;
      console.error(`[consolidation] ${msg}`);
      state.errors.push(msg);
    }
    await new Promise((r) => setTimeout(r, DELAY_MS));
  }

  // Create brand-new pages for topics that didn't match any existing page
  for (const page of newPages) {
    console.log(`[consolidation] Creating new Notion page: "${page.title}"`);
    try {
      await createChildPage(client, parentId, page.title, page.content);
      state.pagesCreated++;
    } catch (err) {
      const msg = `Failed to create "${page.title}": ${err instanceof Error ? err.message : err}`;
      console.error(`[consolidation] ${msg}`);
      state.errors.push(msg);
    }
    await new Promise((r) => setTimeout(r, DELAY_MS));
  }
}

export async function writeToNotion(
  pages: ConsolidatedPage[],
  userId: string,
  state: PipelineState,
): Promise<void> {
  const { getUncachableNotionClient } = await import('../../notion-service');
  const client = await getUncachableNotionClient(userId);

  // Find or create parent page
  const parentId = await findOrCreateParentPage(client);
  state.notionParentId = parentId;

  // Create summary page
  const now = new Date().toISOString().split('T')[0];
  const summaryContent = [
    `# Consolidation Summary`,
    ``,
    `**Date:** ${now}`,
    `**Total documents processed:** ${state.totalDocuments}`,
    `**Topic clusters:** ${state.clusters}`,
    `**Pages created:** ${pages.length}`,
    ``,
    `## Topics`,
    ...pages.map((p) => `- **${p.title}** (${p.category}) — ${p.sourceCount} sources`),
    ``,
    state.errors.length > 0 ? `## Errors\n${state.errors.map((e) => `- ${e}`).join('\n')}` : '',
  ].join('\n');

  await createChildPage(client, parentId, `Consolidation — ${now}`, summaryContent);
  await new Promise((r) => setTimeout(r, DELAY_MS));

  // Create a page for each consolidated topic
  for (let i = 0; i < pages.length; i++) {
    const page = pages[i];
    console.log(`[consolidation] Writing to Notion: "${page.title}" (${i + 1}/${pages.length})`);

    try {
      await createChildPage(client, parentId, page.title, page.content, {
        sourceCount: page.sourceCount,
        category: page.category,
      });
      state.pagesCreated++;
    } catch (err) {
      const msg = `Failed to write "${page.title}" to Notion: ${err instanceof Error ? err.message : err}`;
      console.error(`[consolidation] ${msg}`);
      state.errors.push(msg);
    }

    await new Promise((r) => setTimeout(r, DELAY_MS));
  }
}
